### ISSUE TITLE
Can I throw a Card out of the table from a Hand ?

### ISSUE THREAD

**Issue by ghost** [einaregilsson/cards.js#15]
Can I throw a Card out of the table ? from a Hand ?
I am tring this:

```
discardPile.removeCard(discardPile.topCard())
discardPile.render()
```

but iterating on some or all cards, just make them one level bellow in the appearing hand. I want to literally throw them out the table or back to the deck

thanks !

**Comment by einaregilsson** [comment]
The library doesn't support that. This library was never really finished, I just made a basic version many years ago and haven't touched it since. But if I wanted to completely remove a card I'd probably do something like:

```
var card = discardPile.topCard();
discardPile.removeCard(card);
$(card.el).remove(); // <-- card.el is the actual DOM element, just remove that from the page.
discardPile.render();
```

Or to do it better you might consider adding a parameter to the ```removeCard``` function that lets you completely kill the card when you remove it from the container.

**Comment by ghost** [comment]
well this works great ! thanks a lot. 

Closing this
